// <auto-generated />
namespace Deadliner.Lib.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_LastCall_and_Interval_into_Notification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_LastCall_and_Interval_into_Notification));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141905529_Add_LastCall_and_Interval_into_Notification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
